// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.qcloud.cmq.client.protocol;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface properinfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:properinfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return Whether the msgId field is set.
     */
    boolean hasMsgId();
    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return The msgId.
     */
    long getMsgId();
  }
  /**
   * Protobuf type {@code properinfo}
   */
  public static final class properinfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:properinfo)
      properinfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use properinfo.newBuilder() to construct.
    private properinfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private properinfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new properinfo();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qcloud.cmq.client.protocol.Common.internal_static_properinfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qcloud.cmq.client.protocol.Common.internal_static_properinfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qcloud.cmq.client.protocol.Common.properinfo.class, com.qcloud.cmq.client.protocol.Common.properinfo.Builder.class);
    }

    private int bitField0_;
    public static final int MSG_ID_FIELD_NUMBER = 1;
    private long msgId_ = 0L;
    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return Whether the msgId field is set.
     */
    @java.lang.Override
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public long getMsgId() {
      return msgId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, msgId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, msgId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qcloud.cmq.client.protocol.Common.properinfo)) {
        return super.equals(obj);
      }
      com.qcloud.cmq.client.protocol.Common.properinfo other = (com.qcloud.cmq.client.protocol.Common.properinfo) obj;

      if (hasMsgId() != other.hasMsgId()) return false;
      if (hasMsgId()) {
        if (getMsgId()
            != other.getMsgId()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgId()) {
        hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMsgId());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qcloud.cmq.client.protocol.Common.properinfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qcloud.cmq.client.protocol.Common.properinfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.properinfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qcloud.cmq.client.protocol.Common.properinfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.properinfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qcloud.cmq.client.protocol.Common.properinfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.properinfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qcloud.cmq.client.protocol.Common.properinfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.qcloud.cmq.client.protocol.Common.properinfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.qcloud.cmq.client.protocol.Common.properinfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.properinfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qcloud.cmq.client.protocol.Common.properinfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qcloud.cmq.client.protocol.Common.properinfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code properinfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:properinfo)
        com.qcloud.cmq.client.protocol.Common.properinfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qcloud.cmq.client.protocol.Common.internal_static_properinfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qcloud.cmq.client.protocol.Common.internal_static_properinfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qcloud.cmq.client.protocol.Common.properinfo.class, com.qcloud.cmq.client.protocol.Common.properinfo.Builder.class);
      }

      // Construct using com.qcloud.cmq.client.protocol.Common.properinfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        msgId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qcloud.cmq.client.protocol.Common.internal_static_properinfo_descriptor;
      }

      @java.lang.Override
      public com.qcloud.cmq.client.protocol.Common.properinfo getDefaultInstanceForType() {
        return com.qcloud.cmq.client.protocol.Common.properinfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.qcloud.cmq.client.protocol.Common.properinfo build() {
        com.qcloud.cmq.client.protocol.Common.properinfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.qcloud.cmq.client.protocol.Common.properinfo buildPartial() {
        com.qcloud.cmq.client.protocol.Common.properinfo result = new com.qcloud.cmq.client.protocol.Common.properinfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.qcloud.cmq.client.protocol.Common.properinfo result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.msgId_ = msgId_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qcloud.cmq.client.protocol.Common.properinfo) {
          return mergeFrom((com.qcloud.cmq.client.protocol.Common.properinfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qcloud.cmq.client.protocol.Common.properinfo other) {
        if (other == com.qcloud.cmq.client.protocol.Common.properinfo.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasMsgId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                msgId_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long msgId_ ;
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @return Whether the msgId field is set.
       */
      @java.lang.Override
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @return The msgId.
       */
      @java.lang.Override
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(long value) {

        msgId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:properinfo)
    }

    // @@protoc_insertion_point(class_scope:properinfo)
    private static final com.qcloud.cmq.client.protocol.Common.properinfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qcloud.cmq.client.protocol.Common.properinfo();
    }

    public static com.qcloud.cmq.client.protocol.Common.properinfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<properinfo>
        PARSER = new com.google.protobuf.AbstractParser<properinfo>() {
      @java.lang.Override
      public properinfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<properinfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<properinfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.qcloud.cmq.client.protocol.Common.properinfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface msg_extOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msg_ext)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return Whether the msgId field is set.
     */
    boolean hasMsgId();
    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return The msgId.
     */
    long getMsgId();
  }
  /**
   * Protobuf type {@code msg_ext}
   */
  public static final class msg_ext extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msg_ext)
      msg_extOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use msg_ext.newBuilder() to construct.
    private msg_ext(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private msg_ext() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new msg_ext();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qcloud.cmq.client.protocol.Common.internal_static_msg_ext_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qcloud.cmq.client.protocol.Common.internal_static_msg_ext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qcloud.cmq.client.protocol.Common.msg_ext.class, com.qcloud.cmq.client.protocol.Common.msg_ext.Builder.class);
    }

    private int bitField0_;
    public static final int MSG_ID_FIELD_NUMBER = 1;
    private long msgId_ = 0L;
    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return Whether the msgId field is set.
     */
    @java.lang.Override
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public long getMsgId() {
      return msgId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, msgId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, msgId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qcloud.cmq.client.protocol.Common.msg_ext)) {
        return super.equals(obj);
      }
      com.qcloud.cmq.client.protocol.Common.msg_ext other = (com.qcloud.cmq.client.protocol.Common.msg_ext) obj;

      if (hasMsgId() != other.hasMsgId()) return false;
      if (hasMsgId()) {
        if (getMsgId()
            != other.getMsgId()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgId()) {
        hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMsgId());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qcloud.cmq.client.protocol.Common.msg_ext parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qcloud.cmq.client.protocol.Common.msg_ext parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.msg_ext parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qcloud.cmq.client.protocol.Common.msg_ext parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.msg_ext parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qcloud.cmq.client.protocol.Common.msg_ext parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.msg_ext parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qcloud.cmq.client.protocol.Common.msg_ext parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.qcloud.cmq.client.protocol.Common.msg_ext parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.qcloud.cmq.client.protocol.Common.msg_ext parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.msg_ext parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qcloud.cmq.client.protocol.Common.msg_ext parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qcloud.cmq.client.protocol.Common.msg_ext prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msg_ext}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msg_ext)
        com.qcloud.cmq.client.protocol.Common.msg_extOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qcloud.cmq.client.protocol.Common.internal_static_msg_ext_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qcloud.cmq.client.protocol.Common.internal_static_msg_ext_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qcloud.cmq.client.protocol.Common.msg_ext.class, com.qcloud.cmq.client.protocol.Common.msg_ext.Builder.class);
      }

      // Construct using com.qcloud.cmq.client.protocol.Common.msg_ext.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        msgId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qcloud.cmq.client.protocol.Common.internal_static_msg_ext_descriptor;
      }

      @java.lang.Override
      public com.qcloud.cmq.client.protocol.Common.msg_ext getDefaultInstanceForType() {
        return com.qcloud.cmq.client.protocol.Common.msg_ext.getDefaultInstance();
      }

      @java.lang.Override
      public com.qcloud.cmq.client.protocol.Common.msg_ext build() {
        com.qcloud.cmq.client.protocol.Common.msg_ext result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.qcloud.cmq.client.protocol.Common.msg_ext buildPartial() {
        com.qcloud.cmq.client.protocol.Common.msg_ext result = new com.qcloud.cmq.client.protocol.Common.msg_ext(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.qcloud.cmq.client.protocol.Common.msg_ext result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.msgId_ = msgId_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qcloud.cmq.client.protocol.Common.msg_ext) {
          return mergeFrom((com.qcloud.cmq.client.protocol.Common.msg_ext)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qcloud.cmq.client.protocol.Common.msg_ext other) {
        if (other == com.qcloud.cmq.client.protocol.Common.msg_ext.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasMsgId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                msgId_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long msgId_ ;
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @return Whether the msgId field is set.
       */
      @java.lang.Override
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @return The msgId.
       */
      @java.lang.Override
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(long value) {

        msgId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msg_ext)
    }

    // @@protoc_insertion_point(class_scope:msg_ext)
    private static final com.qcloud.cmq.client.protocol.Common.msg_ext DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qcloud.cmq.client.protocol.Common.msg_ext();
    }

    public static com.qcloud.cmq.client.protocol.Common.msg_ext getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<msg_ext>
        PARSER = new com.google.protobuf.AbstractParser<msg_ext>() {
      @java.lang.Override
      public msg_ext parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<msg_ext> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<msg_ext> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.qcloud.cmq.client.protocol.Common.msg_ext getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface producedataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:producedata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return Whether the msgId field is set.
     */
    boolean hasMsgId();
    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return The msgId.
     */
    long getMsgId();
  }
  /**
   * Protobuf type {@code producedata}
   */
  public static final class producedata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:producedata)
      producedataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use producedata.newBuilder() to construct.
    private producedata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private producedata() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new producedata();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qcloud.cmq.client.protocol.Common.internal_static_producedata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qcloud.cmq.client.protocol.Common.internal_static_producedata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qcloud.cmq.client.protocol.Common.producedata.class, com.qcloud.cmq.client.protocol.Common.producedata.Builder.class);
    }

    private int bitField0_;
    public static final int MSG_ID_FIELD_NUMBER = 1;
    private long msgId_ = 0L;
    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return Whether the msgId field is set.
     */
    @java.lang.Override
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public long getMsgId() {
      return msgId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, msgId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, msgId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qcloud.cmq.client.protocol.Common.producedata)) {
        return super.equals(obj);
      }
      com.qcloud.cmq.client.protocol.Common.producedata other = (com.qcloud.cmq.client.protocol.Common.producedata) obj;

      if (hasMsgId() != other.hasMsgId()) return false;
      if (hasMsgId()) {
        if (getMsgId()
            != other.getMsgId()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgId()) {
        hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMsgId());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qcloud.cmq.client.protocol.Common.producedata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qcloud.cmq.client.protocol.Common.producedata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.producedata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qcloud.cmq.client.protocol.Common.producedata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.producedata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qcloud.cmq.client.protocol.Common.producedata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.producedata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qcloud.cmq.client.protocol.Common.producedata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.qcloud.cmq.client.protocol.Common.producedata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.qcloud.cmq.client.protocol.Common.producedata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.producedata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qcloud.cmq.client.protocol.Common.producedata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qcloud.cmq.client.protocol.Common.producedata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code producedata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:producedata)
        com.qcloud.cmq.client.protocol.Common.producedataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qcloud.cmq.client.protocol.Common.internal_static_producedata_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qcloud.cmq.client.protocol.Common.internal_static_producedata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qcloud.cmq.client.protocol.Common.producedata.class, com.qcloud.cmq.client.protocol.Common.producedata.Builder.class);
      }

      // Construct using com.qcloud.cmq.client.protocol.Common.producedata.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        msgId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qcloud.cmq.client.protocol.Common.internal_static_producedata_descriptor;
      }

      @java.lang.Override
      public com.qcloud.cmq.client.protocol.Common.producedata getDefaultInstanceForType() {
        return com.qcloud.cmq.client.protocol.Common.producedata.getDefaultInstance();
      }

      @java.lang.Override
      public com.qcloud.cmq.client.protocol.Common.producedata build() {
        com.qcloud.cmq.client.protocol.Common.producedata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.qcloud.cmq.client.protocol.Common.producedata buildPartial() {
        com.qcloud.cmq.client.protocol.Common.producedata result = new com.qcloud.cmq.client.protocol.Common.producedata(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.qcloud.cmq.client.protocol.Common.producedata result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.msgId_ = msgId_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qcloud.cmq.client.protocol.Common.producedata) {
          return mergeFrom((com.qcloud.cmq.client.protocol.Common.producedata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qcloud.cmq.client.protocol.Common.producedata other) {
        if (other == com.qcloud.cmq.client.protocol.Common.producedata.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasMsgId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                msgId_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long msgId_ ;
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @return Whether the msgId field is set.
       */
      @java.lang.Override
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @return The msgId.
       */
      @java.lang.Override
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(long value) {

        msgId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:producedata)
    }

    // @@protoc_insertion_point(class_scope:producedata)
    private static final com.qcloud.cmq.client.protocol.Common.producedata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qcloud.cmq.client.protocol.Common.producedata();
    }

    public static com.qcloud.cmq.client.protocol.Common.producedata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<producedata>
        PARSER = new com.google.protobuf.AbstractParser<producedata>() {
      @java.lang.Override
      public producedata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<producedata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<producedata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.qcloud.cmq.client.protocol.Common.producedata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface consumedataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:consumedata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return Whether the msgId field is set.
     */
    boolean hasMsgId();
    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return The msgId.
     */
    long getMsgId();
  }
  /**
   * Protobuf type {@code consumedata}
   */
  public static final class consumedata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:consumedata)
      consumedataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use consumedata.newBuilder() to construct.
    private consumedata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private consumedata() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new consumedata();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qcloud.cmq.client.protocol.Common.internal_static_consumedata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qcloud.cmq.client.protocol.Common.internal_static_consumedata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qcloud.cmq.client.protocol.Common.consumedata.class, com.qcloud.cmq.client.protocol.Common.consumedata.Builder.class);
    }

    private int bitField0_;
    public static final int MSG_ID_FIELD_NUMBER = 1;
    private long msgId_ = 0L;
    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return Whether the msgId field is set.
     */
    @java.lang.Override
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public long getMsgId() {
      return msgId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, msgId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, msgId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qcloud.cmq.client.protocol.Common.consumedata)) {
        return super.equals(obj);
      }
      com.qcloud.cmq.client.protocol.Common.consumedata other = (com.qcloud.cmq.client.protocol.Common.consumedata) obj;

      if (hasMsgId() != other.hasMsgId()) return false;
      if (hasMsgId()) {
        if (getMsgId()
            != other.getMsgId()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgId()) {
        hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMsgId());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qcloud.cmq.client.protocol.Common.consumedata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qcloud.cmq.client.protocol.Common.consumedata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.consumedata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qcloud.cmq.client.protocol.Common.consumedata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.consumedata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qcloud.cmq.client.protocol.Common.consumedata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.consumedata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qcloud.cmq.client.protocol.Common.consumedata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.qcloud.cmq.client.protocol.Common.consumedata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.qcloud.cmq.client.protocol.Common.consumedata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.consumedata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qcloud.cmq.client.protocol.Common.consumedata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qcloud.cmq.client.protocol.Common.consumedata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code consumedata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:consumedata)
        com.qcloud.cmq.client.protocol.Common.consumedataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qcloud.cmq.client.protocol.Common.internal_static_consumedata_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qcloud.cmq.client.protocol.Common.internal_static_consumedata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qcloud.cmq.client.protocol.Common.consumedata.class, com.qcloud.cmq.client.protocol.Common.consumedata.Builder.class);
      }

      // Construct using com.qcloud.cmq.client.protocol.Common.consumedata.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        msgId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qcloud.cmq.client.protocol.Common.internal_static_consumedata_descriptor;
      }

      @java.lang.Override
      public com.qcloud.cmq.client.protocol.Common.consumedata getDefaultInstanceForType() {
        return com.qcloud.cmq.client.protocol.Common.consumedata.getDefaultInstance();
      }

      @java.lang.Override
      public com.qcloud.cmq.client.protocol.Common.consumedata build() {
        com.qcloud.cmq.client.protocol.Common.consumedata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.qcloud.cmq.client.protocol.Common.consumedata buildPartial() {
        com.qcloud.cmq.client.protocol.Common.consumedata result = new com.qcloud.cmq.client.protocol.Common.consumedata(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.qcloud.cmq.client.protocol.Common.consumedata result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.msgId_ = msgId_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qcloud.cmq.client.protocol.Common.consumedata) {
          return mergeFrom((com.qcloud.cmq.client.protocol.Common.consumedata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qcloud.cmq.client.protocol.Common.consumedata other) {
        if (other == com.qcloud.cmq.client.protocol.Common.consumedata.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasMsgId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                msgId_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long msgId_ ;
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @return Whether the msgId field is set.
       */
      @java.lang.Override
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @return The msgId.
       */
      @java.lang.Override
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(long value) {

        msgId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:consumedata)
    }

    // @@protoc_insertion_point(class_scope:consumedata)
    private static final com.qcloud.cmq.client.protocol.Common.consumedata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qcloud.cmq.client.protocol.Common.consumedata();
    }

    public static com.qcloud.cmq.client.protocol.Common.consumedata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<consumedata>
        PARSER = new com.google.protobuf.AbstractParser<consumedata>() {
      @java.lang.Override
      public consumedata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<consumedata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<consumedata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.qcloud.cmq.client.protocol.Common.consumedata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface offsettableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:offsettable)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return Whether the msgId field is set.
     */
    boolean hasMsgId();
    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return The msgId.
     */
    long getMsgId();
  }
  /**
   * Protobuf type {@code offsettable}
   */
  public static final class offsettable extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:offsettable)
      offsettableOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use offsettable.newBuilder() to construct.
    private offsettable(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private offsettable() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new offsettable();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qcloud.cmq.client.protocol.Common.internal_static_offsettable_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qcloud.cmq.client.protocol.Common.internal_static_offsettable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qcloud.cmq.client.protocol.Common.offsettable.class, com.qcloud.cmq.client.protocol.Common.offsettable.Builder.class);
    }

    private int bitField0_;
    public static final int MSG_ID_FIELD_NUMBER = 1;
    private long msgId_ = 0L;
    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return Whether the msgId field is set.
     */
    @java.lang.Override
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *msg ID
     * </pre>
     *
     * <code>required uint64 msg_id = 1;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public long getMsgId() {
      return msgId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, msgId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, msgId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qcloud.cmq.client.protocol.Common.offsettable)) {
        return super.equals(obj);
      }
      com.qcloud.cmq.client.protocol.Common.offsettable other = (com.qcloud.cmq.client.protocol.Common.offsettable) obj;

      if (hasMsgId() != other.hasMsgId()) return false;
      if (hasMsgId()) {
        if (getMsgId()
            != other.getMsgId()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgId()) {
        hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMsgId());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qcloud.cmq.client.protocol.Common.offsettable parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qcloud.cmq.client.protocol.Common.offsettable parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.offsettable parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qcloud.cmq.client.protocol.Common.offsettable parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.offsettable parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qcloud.cmq.client.protocol.Common.offsettable parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.offsettable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qcloud.cmq.client.protocol.Common.offsettable parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.qcloud.cmq.client.protocol.Common.offsettable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.qcloud.cmq.client.protocol.Common.offsettable parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qcloud.cmq.client.protocol.Common.offsettable parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qcloud.cmq.client.protocol.Common.offsettable parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qcloud.cmq.client.protocol.Common.offsettable prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code offsettable}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:offsettable)
        com.qcloud.cmq.client.protocol.Common.offsettableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qcloud.cmq.client.protocol.Common.internal_static_offsettable_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qcloud.cmq.client.protocol.Common.internal_static_offsettable_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qcloud.cmq.client.protocol.Common.offsettable.class, com.qcloud.cmq.client.protocol.Common.offsettable.Builder.class);
      }

      // Construct using com.qcloud.cmq.client.protocol.Common.offsettable.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        msgId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qcloud.cmq.client.protocol.Common.internal_static_offsettable_descriptor;
      }

      @java.lang.Override
      public com.qcloud.cmq.client.protocol.Common.offsettable getDefaultInstanceForType() {
        return com.qcloud.cmq.client.protocol.Common.offsettable.getDefaultInstance();
      }

      @java.lang.Override
      public com.qcloud.cmq.client.protocol.Common.offsettable build() {
        com.qcloud.cmq.client.protocol.Common.offsettable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.qcloud.cmq.client.protocol.Common.offsettable buildPartial() {
        com.qcloud.cmq.client.protocol.Common.offsettable result = new com.qcloud.cmq.client.protocol.Common.offsettable(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.qcloud.cmq.client.protocol.Common.offsettable result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.msgId_ = msgId_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qcloud.cmq.client.protocol.Common.offsettable) {
          return mergeFrom((com.qcloud.cmq.client.protocol.Common.offsettable)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qcloud.cmq.client.protocol.Common.offsettable other) {
        if (other == com.qcloud.cmq.client.protocol.Common.offsettable.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasMsgId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                msgId_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long msgId_ ;
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @return Whether the msgId field is set.
       */
      @java.lang.Override
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @return The msgId.
       */
      @java.lang.Override
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(long value) {

        msgId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *msg ID
       * </pre>
       *
       * <code>required uint64 msg_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:offsettable)
    }

    // @@protoc_insertion_point(class_scope:offsettable)
    private static final com.qcloud.cmq.client.protocol.Common.offsettable DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qcloud.cmq.client.protocol.Common.offsettable();
    }

    public static com.qcloud.cmq.client.protocol.Common.offsettable getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<offsettable>
        PARSER = new com.google.protobuf.AbstractParser<offsettable>() {
      @java.lang.Override
      public offsettable parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<offsettable> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<offsettable> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.qcloud.cmq.client.protocol.Common.offsettable getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_properinfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_properinfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_ext_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msg_ext_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_producedata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_producedata_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_consumedata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_consumedata_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_offsettable_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_offsettable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\"\034\n\nproperinfo\022\016\n\006msg_id\030\001" +
      " \002(\004\"\031\n\007msg_ext\022\016\n\006msg_id\030\001 \002(\004\"\035\n\013produ" +
      "cedata\022\016\n\006msg_id\030\001 \002(\004\"\035\n\013consumedata\022\016\n" +
      "\006msg_id\030\001 \002(\004\"\035\n\013offsettable\022\016\n\006msg_id\030\001" +
      " \002(\004B \n\036com.qcloud.cmq.client.protocol"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_properinfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_properinfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_properinfo_descriptor,
        new java.lang.String[] { "MsgId", });
    internal_static_msg_ext_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_msg_ext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msg_ext_descriptor,
        new java.lang.String[] { "MsgId", });
    internal_static_producedata_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_producedata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_producedata_descriptor,
        new java.lang.String[] { "MsgId", });
    internal_static_consumedata_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_consumedata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_consumedata_descriptor,
        new java.lang.String[] { "MsgId", });
    internal_static_offsettable_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_offsettable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_offsettable_descriptor,
        new java.lang.String[] { "MsgId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
